
// auth actions
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const DO_LOGOUT = 'DO_LOGOUT';
export const DO_LOGOUT_SUCCESS = 'DO_LOGOUT_SUCCESS';

export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
// notifications actions
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// session actions
export const PREPARE_SESSION = 'PREPARE_SESSION';
export const START_SESSION = 'START_SESSION';
export const FINISH_SESSION = 'FINISH_SESSION';

export const START_SESSION_SUCCESS = 'START_SESSION_SUCCESS';
export const START_SESSION_ERROR = 'START_SESSION_ERROR';
export const FINISH_SESSION_SUCCESS = 'FINISH_SESSION_SUCCESS';
export const FINISH_SESSION_ERROR = 'FINISH_SESSION_ERROR';
