
// auth actions
export const DO_LOGIN = 'DO_LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const DO_OAUTH_LOGIN = 'DO_OAUTH_LOGIN';
export const LOGIN_OAUTH_SUCCESS = 'LOGIN_OAUTH_SUCCESS';

export const DO_LOGOUT = 'DO_LOGOUT';
export const DO_LOGOUT_SUCCESS = 'DO_LOGOUT_SUCCESS';

export const DO_REGISTER = 'DO_REGISTER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';

export const DO_UPDATE_USER = 'DO_UPDATE_USER';
export const DO_UPDATE_USER_SUCCESS = 'DO_UPDATE_USER_SUCCESS';
export const DO_UPDATE_USER_ERROR = 'DO_UPDATE_USER_ERROR';

export const DO_UPDATE_PROFILE = 'DO_UPDATE_PROFILE';
export const DO_UPDATE_PROFILE_SUCCESS = 'DO_UPDATE_PROFILE_SUCCESS';
export const DO_UPDATE_PROFILE_ERROR = 'DO_UPDATE_PROFILE_ERROR';


// notifications actions
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

// For real time. Observable actions
export const ADD_OBSERVABLE = 'ADD_OBSERVABLE';
export const REMOVE_OBSERVABLE = 'REMOVE_OBSERVABLE';

export const UPDATE_ATLETE_POSITION_SUCCESS = 'UPDATE_ATLETE_POSITION_SUCCESS';

// session actions
export const PREPARE_SESSION = 'PREPARE_SESSION';
export const PREPARE_SESSION_SUCCESS = 'PREPARE_SESSION_SUCCESS';
export const START_SESSION = 'START_SESSION';
export const FINISH_SESSION = 'FINISH_SESSION';

export const UPDATE_SESSION_POSITION = 'UPDATE_SESSION_POSITION';
export const UPDATE_SESSION_POSITION_SUCCESS = 'UPDATE_SESSION_POSITION_SUCCESS';

export const START_SESSION_SUCCESS = 'START_SESSION_SUCCESS';
export const START_SESSION_ERROR = 'START_SESSION_ERROR';
export const FINISH_SESSION_SUCCESS = 'FINISH_SESSION_SUCCESS';
export const FINISH_SESSION_ERROR = 'FINISH_SESSION_ERROR';

export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const CREATE_EXERCISE_SUCCESS = 'CREATE_EXERCISE_SUCCESS';
export const CREATE_EXERCISE_ERROR = 'CREATE_EXERCISE_ERROR';
export const GET_EXERCISES = 'GET_EXERCISES';
export const GET_EXERCISES_SUCCESS = 'GET_EXERCISES_SUCCESS';
export const GET_EXERCISES_ERROR = 'GET_EXERCISES_SUCCESS';

export const CREATE_ROUTINE = 'CREATE_ROUTINE';
export const CREATE_ROUTINE_SUCCESS = 'CREATE_ROUTINE_SUCCESS';
export const CREATE_ROUTINE_ERROR = 'CREATE_ROUTINE_ERROR';

export const GET_ALL_ROUTINES = 'GET_ALL_ROUTINES';
export const GET_ALL_ROUTINES_SUCCESS = 'GET_ALL_ROUTINES_SUCCESS';
export const GET_ALL_ROUTINES_ERROR = 'GET_ALL_ROUTINES_ERROR';

export const GET_IMAGES = 'GET_IMAGES';
export const GET_IMAGES_SUCCESS = 'GET_IMAGES_SUCCESS';

export const RETRIEVE_STATS_DATA = 'RETRIEVE_STATS_DATA';
export const RETRIEVE_STATS_DATA_SUCCESS = 'RETRIEVE_STATS_DATA_SUCCESS';
export const RETRIEVE_STATS_DATA_ERROR = 'RETRIEVE_STATS_DATA_ERROR';
